apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yfys12wa7-python
  janus-idp.io/tekton: yfys12wa7-python
  backstage.io/kubernetes-id: yfys12wa7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yfys12wa7-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
