apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yfys12wa7-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yfys12wa7-python 
  name: yfys12wa7-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yfys12wa7-python 
